name: Deploy multicontainer app
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ch4ku/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ch4ku/react-test npm test
 
      - run: docker build -t ch4ku/multi-client-20 ./client
      - run: docker build -t ch4ku/multi-nginx-20 ./nginx
      - run: docker build -t ch4ku/multi-server-20 ./server
      - run: docker build -t ch4ku/multi-worker-20 ./worker
 
      - run: docker push ch4ku/multi-client-20
      - run: docker push ch4ku/multi-nginx-20
      - run: docker push ch4ku/multi-server-20
      - run: docker push ch4ku/multi-worker-20

  build-and-test-with-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-application
          environment_name: Docker-application-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-503600729669
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
